baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
pluralizeListTitles = false
title = "Aron"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[params]
custom_css = ["css/theme-override.css"]
description = "Aron's site"
footer = "[About this website](https://aron.nyc/website/) | Thanks for visiting!"
