baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
pluralizeListTitles = false
title = "aron online!"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
projects = "/projects/:slug/"
writing = "/writing/:slug/"
culture = "/culture/:slug/"

[[menu.main]]
name = "projects"
url = "/projects/"
weight = 1
[[menu.main]]
name = "writing"
url = "/writing/"
weight = 2
[[menu.main]]
name = "culture"
url = "/culture/"
weight = 3

[params]
custom_css = ["css/theme-override.css"]
description = "aron online!"
footer = "[privacy policy](/privacy/) | [song recommendation](https://soundcloud.com/sebastianvydra/nothingtofear)"
