baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
pluralizeListTitles = false
title = "Aron"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
About = "/about/"
Dumb = "/projects/:slug/"
writing = "/writing/:slug/"
media = "/media/:slug/"

[[menu.main]]
name = "I Like"
url = "/projects/"
weight = 1
[[menu.main]]
name = "writing"
url = "/writing/"
weight = 2
[[menu.main]]
name = "media"
url = "/media/"
weight = 3

[params]
custom_css = ["css/theme-override.css"]
description = "Aron"
footer = "[My web philosophy](/web-philosophy/) | [Song recommendation](https://soundcloud.com/sebastianvydra/nothingtofear)"
