baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
pluralizeListTitles = false
title = "Aron"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
personal = "/personal/:slug/"
professional = "/professional/:slug/"

[[menu.main]]
name = "Personal"
url = "/personal/"
weight = 1
[[menu.main]]
name = "Professional"
url = "/professional/"
weight = 2

[params]
custom_css = ["css/theme-override.css"]
description = "Aron"
footer = "[Web ethos](/web-ethos/) | [Song recommendation](https://sebastianvydra.bandcamp.com/track/nothing-to-fear)"
